# Netlify configuration for frontend hosting.
# Redirect /api/* calls to backend. Replace BACKEND_URL with your Northflank HTTPS URL.

[[redirects]]
  from = "/api/*"
  to = "https://tikcash.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/openapi.json"
  to = "https://tikcash.onrender.com/openapi.json"
  status = 200
  force = true
